services:
  movieapi:
    build:
      context: .
      dockerfile: MovieApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=MovieDb;User Id=sa;Password=MovieApi_Test123!;TrustServerCertificate=True;"
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MovieApi_Test123!"